export const BLOCK_GET_ALL_REQUEST = 'BLOCK_GET_ALL_REQUEST';
export const BLOCK_GET_ALL_SUCCESS = 'BLOCK_GET_ALL_SUCCESS';
export const BLOCK_GET_ALL_FAIL = 'BLOCK_GET_ALL_FAIL';

export const BLOCK_USER_REQUEST = 'BLOCK_USER_REQUEST';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_FAIL = 'BLOCK_USER_FAIL';
export const BLOCK_USER_RESET = 'BLOCK_USER_RESET';

export const UNBLOCK_USER_REQUEST = 'UNBLOCK_USER_REQUEST';
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS';
export const UNBLOCK_USER_FAIL = 'UNBLOCK_USER_FAIL';
export const UNBLOCK_USER_RESET = 'UNBLOCK_USER_RESET';
