export const CHAT_GET_ALL_REQUEST = "CHAT_GET_ALL_REQUEST";
export const CHAT_GET_ALL_SUCCESS = "CHAT_GET_ALL_SUCCESS";
export const CHAT_GET_ALL_FAIL = "CHAT_GET_ALL_FAIL";

export const CHAT_DELETE_REQUEST = "CHAT_DELETE_REQUEST";
export const CHAT_DELETE_SUCCESS = "CHAT_DELETE_SUCCESS";
export const CHAT_DELETE_FAIL = "CHAT_DELETE_FAIL";
