export const FOLLOWER_GET_REQUEST = 'FOLLOWER_GET_REQUEST';
export const FOLLOWER_GET_SUCCESS = 'FOLLOWER_GET_SUCCESS';
export const FOLLOWER_GET_FAIL = 'FOLLOWER_GET_FAIL';

export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAIL = 'FOLLOW_USER_FAIL';
export const FOLLOW_USER_RESET = 'FOLLOW_USER_RESET';

export const UNFOLLOW_USER_REQUEST = 'UNFOLLOW_USER_REQUEST';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_FAIL = 'UNFOLLOW_USER_FAIL';
export const UNFOLLOW_USER_RESET = 'UNFOLLOW_USER_RESET';
