export const NOTIFICATION_GET_REQUEST = "NOTIFICATION_GET_REQUEST";
export const NOTIFICATION_GET_SUCCESS = "NOTIFICATION_GET_SUCCESS";
export const NOTIFICATION_GET_FAIL = "NOTIFICATION_GET_FAIL";

export const NOTIFICATION_READ_REQUEST = "NOTIFICATION_READ_REQUEST";
export const NOTIFICATION_READ_SUCCESS = "NOTIFICATION_READ_SUCCESS";
export const NOTIFICATION_READ_FAIL = "NOTIFICATION_READ_FAIL";
