export const POST_GET_ALL_REQUEST = "POST_GET_ALL_REQUEST";
export const POST_GET_ALL_SUCCESS = "POST_GET_ALL_SUCCESS";
export const POST_GET_ALL_FAIL = "POST_GET_ALL_FAIL";
export const POST_GET_ALL_RESET = "POST_GET_ALL_RESET";

export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";

export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAIL = "POST_DELETE_FAIL";

export const POST_LIKE_REQUEST = "POST_LIKE_REQUEST";
export const POST_LIKE_SUCCESS = "POST_LIKE_SUCCESS";
export const POST_LIKE_FAIL = "POST_LIKE_FAIL";

export const POST_UNLIKE_REQUEST = "POST_UNLIKE_REQUEST";
export const POST_UNLIKE_SUCCESS = "POST_UNLIKE_SUCCESS";
export const POST_UNLIKE_FAIL = "POST_UNLIKE_FAIL";

export const POST_CREATE_COMMENT_REQUEST = "POST_CREATE_COMMENT_REQUEST";
export const POST_CREATE_COMMENT_SUCCESS = "POST_CREATE_COMMENT_SUCCESS";
export const POST_CREATE_COMMENT_FAIL = "POST_CREATE_COMMENT_FAIL";

export const POST_DELETE_COMMENT_REQUEST = "POST_DELETE_COMMENT_REQUEST";
export const POST_DELETE_COMMENT_SUCCESS = "POST_DELETE_COMMENT_SUCCESS";
export const POST_DELETE_COMMENT_FAIL = "POST_DELETE_COMMENT_FAIL";

export const POST_GET_LIKES_LIST_REQUEST = "POST_GET_LIKES_LIST_REQUEST";
export const POST_GET_LIKES_LIST_SUCCESS = "POST_GET_LIKES_LIST_SUCCESS";
export const POST_GET_LIKES_LIST_FAIL = "POST_GET_LIKES_LIST_FAIL";

export const POST_GET_BY_ID_REQUEST = "POST_GET_BY_ID_REQUEST";
export const POST_GET_BY_ID_SUCCESS = "POST_GET_BY_ID_SUCCESS";
export const POST_GET_BY_ID_FAIL = "POST_GET_BY_ID_FAIL";
