export const PROFILE_CHECK_IS_BLOCKED_REQUEST = 'PROFILE_CHECK_IS_BLOCKED_REQUEST';
export const PROFILE_CHECK_IS_BLOCKED_SUCCESS = 'PROFILE_CHECK_IS_BLOCKED_SUCCESS';
export const PROFILE_CHECK_IS_BLOCKED_FAIL = 'PROFILE_CHECK_IS_BLOCKED_FAIL';

export const PROFILE_GET_REQUEST = 'PROFILE_GET_REQUEST';
export const PROFILE_GET_SUCCESS = 'PROFILE_GET_SUCCESS';
export const PROFILE_GET_FAIL = 'PROFILE_GET_FAIL';

export const PROFILE_GET_POSTS_REQUEST = 'PROFILE_GET_POSTS_REQUEST';
export const PROFILE_GET_POSTS_SUCESS = 'PROFILE_GET_POSTS_SUCESS';
export const PROFILE_GET_POSTS_FAIL = 'PROFILE_GET_POSTS_FAIL';

export const PROFILE_GET_FOLLOWERS_BY_USERID_REQUEST = 'PROFILE_GET_FOLLOWERS_BY_USERID_REQUEST';
export const PROFILE_GET_FOLLOWERS_BY_USERID_SUCCESS = 'PROFILE_GET_FOLLOWERS_BY_USERID_SUCCESS';
export const PROFILE_GET_FOLLOWERS_BY_USERID_FAIL = 'PROFILE_GET_FOLLOWERS_BY_USERID_FAIL';

export const PROFILE_GET_FOLLOWING_BY_USERID_REQUEST = 'PROFILE_GET_FOLLOWING_BY_USERID_REQUEST';
export const PROFILE_GET_FOLLOWING_BY_USERID_SUCCESS = 'PROFILE_GET_FOLLOWING_BY_USERID_SUCCESS';
export const PROFILE_GET_FOLLOWING_BY_USERID_FAIL = 'PROFILE_GET_FOLLOWING_BY_USERID_FAIL';

export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';
export const PROFILE_UPDATE_RESET = 'PROFILE_UPDATE_RESET';
