export const REPORT_SEND_REQUEST = 'REPORT_SEND_REQUEST';
export const REPORT_SEND_SUCCESS = 'REPORT_SEND_SUCCESS';
export const REPORT_SEND_FAIL = 'REPORT_SEND_FAIL';
export const REPORT_SEND_RESET = 'REPORT_SEND_RESET';
