export const UTIL_UPLOAD_IMAGE_REQUEST = "UTIL_UPLOAD_IMAGE_REQUEST";
export const UTIL_UPLOAD_IMAGE_SUCESS = "UTIL_UPLOAD_IMAGE_SUCESS";
export const UTIL_UPLOAD_IMAGE_FAIL = "UTIL_UPLOAD_IMAGE_FAIL";
export const UTIL_UPLOAD_IMAGE_RESET = "UTIL_UPLOAD_IMAGE_RESET";

export const UTIL_DELETE_IMAGE_REQUEST = "UTIL_DELETE_IMAGE_REQUEST";
export const UTIL_DELETE_IMAGE_SUCCESS = "UTIL_DELETE_IMAGE_SUCCESS";
export const UTIL_DELETE_IMAGE_FAIL = "UTIL_DELETE_IMAGE_FAIL";
